### ISSUE TITLE
CLI.py - string with no pop method

### ISSUE THREAD

**Issue by arvoshift** [jeansch/py-asterisk#25]
The method execute_action takes a string for argv from command_line.
I've tried using .split without success.

-bash-4.1$ python py-asterisk command "ZapShowChannels"
Traceback (most recent call last):
  File "py-asterisk", line 19, in <module>
    sys.exit(Asterisk.CLI.command_line(sys.argv))
  File "/home/benp/staging/py-Asterisk-0.5.10/Asterisk/CLI.py", line 148, in command_line
    execute_action('command', argv[2])
  File "/home/benp/staging/py-Asterisk-0.5.10/Asterisk/CLI.py", line 84, in execute_action
    method_name = argv.pop(0).lower()
AttributeError: 'str' object has no attribute 'pop'

**Comment by mouseratti** [comment]
@arvoshift I'll try to debug it on weekend

**Comment by jeansch** [comment]
Fixed
