### ISSUE TITLE
trying to use your example to grab the caller ID

### ISSUE THREAD

**Issue by dummys** [jeansch/py-asterisk#9]
Hi,

I'm trying to play with your example and i get an error:

Traceback (most recent call last):
  File "test.py", line 67, in <module>
    grab.register(pbx)
  File "test.py", line 49, in register
    some_pbx.events += events
NameError: global name 'events' is not defined

Are you sure your example is working ?

**Comment by dummys** [comment]
ok i replace with self.events and it's launch but when I place a call i get: 

  File "test.py", line 71, in <module>
    pbx.serve_forever()
  File "/usr/local/lib/python2.7/dist-packages/Asterisk/Manager.py", line 479, in serve_forever
    self._dispatch_packet(packet)
  File "/usr/local/lib/python2.7/dist-packages/Asterisk/Manager.py", line 384, in _dispatch_packet
    self.on_Event(packet)
  File "/usr/local/lib/python2.7/dist-packages/Asterisk/Manager.py", line 467, in on_Event
    self.events.fire(event.Event, self, event)
  File "/usr/local/lib/python2.7/dist-packages/Asterisk/Util.py", line 100, in fire
    return_value = subscription(*args, **kwargs)
  File "test.py", line 12, in Newchannel
    cli = event.Callerid
  File "/usr/local/lib/python2.7/dist-packages/Asterisk/Util.py", line 37, in __getattr__
    return self[key]
KeyError: 'Callerid'

**Comment by dummys** [comment]
Ok it's ok I replace callerid by Exten
